using System.Text;
using Dev.JoshBrunton.DynamicsEndpointDiscovery.Lib.Ax.Services.Soap;
using Dev.JoshBrunton.DynamicsEndpointDiscovery.Lib.Ax.Types;
using Dev.JoshBrunton.DynamicsEndpointDiscovery.Lib.Ax.Types.Soap;

namespace Dev.JoshBrunton.DynamicsEndpointDiscovery.Application.Services.CollectionBuilders;

public class CSharpCollectionBuilder : CollectionBuilderBase<string>
{
    protected override string BuildTypedCollection(
        IEnumerable<DynSvcGroup> groups,
        SoapTypeCollection types,
        string resource,
        string collectionName = "Collection")
    {
        var validDefinitions = types.Definitions
            .Where(x => HasUsableTypeName(x.Name))
            .ToList();
        var definitionsByName = validDefinitions.ToDictionary(x => x.Name, StringComparer.Ordinal);
        var referencedTypeNames = GetReferencedTypeNames(groups, validDefinitions)
            .OrderBy(x => x, StringComparer.Ordinal)
            .ToList();

        StringBuilder sb = new();

        sb.AppendLine($"""
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //     Environment: {resource}
            //     Date: {DateTime.Now:O}
            //
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------
            """);
        sb.AppendLine("// ReSharper disable All");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.Hosting;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using Newtonsoft.Json;");
        sb.AppendLine();
        sb.AppendLine("#region interfaces");
        sb.AppendLine("public interface IAxCallingService");
        sb.AppendLine("{");
        sb.AppendLine("    Task<TResponse> MakeRequestAsync<TRequest, TResponse>(TRequest request, string groupName, string serviceName, string opName, CancellationToken ct);");
        sb.AppendLine("}");
        sb.AppendLine();

        for (int i = 0; i < referencedTypeNames.Count; i++)
        {
            var typeName = referencedTypeNames[i];
            if (definitionsByName.TryGetValue(typeName, out var definition))
            {
                AppendInterface(sb, definition);
            }
            else
            {
                AppendUnknownInterface(sb, typeName);
            }

            if (i != referencedTypeNames.Count - 1)
            {
                sb.AppendLine();
                sb.AppendLine();
            }
        }

        sb.AppendLine("#endregion");
        sb.AppendLine();
        sb.AppendLine("#region implementations");

        for (int i = 0; i < referencedTypeNames.Count; i++)
        {
            var typeName = referencedTypeNames[i];
            if (definitionsByName.TryGetValue(typeName, out var definition))
            {
                AppendImplementation(sb, definition);
            }
            else
            {
                AppendUnknownImplementation(sb, typeName);
            }

            if (i != referencedTypeNames.Count - 1)
            {
                sb.AppendLine();
                sb.AppendLine();
            }
        }

        sb.AppendLine("#endregion");
        sb.AppendLine();
        sb.AppendLine("#region services");

        AppendServices(sb, groups);

        sb.AppendLine("#endregion");
        sb.AppendLine();
        sb.AppendLine("#region registration");

        AppendRegistrationExtensions(sb, groups);

        sb.AppendLine("#endregion");

        return sb.ToString().TrimEnd();
    }

    private static HashSet<string> GetReferencedTypeNames(
        IEnumerable<DynSvcGroup> groups,
        IEnumerable<AxDataContractDefn> definitions)
    {
        HashSet<string> typeNames = new(StringComparer.Ordinal);

        foreach (var definition in definitions)
        {
            if (!SoapPrimitiveTypes.IsPrimitive(definition.Name))
            {
                typeNames.Add(definition.Name);
            }

            if (!string.IsNullOrWhiteSpace(definition.Extends) && !SoapPrimitiveTypes.IsPrimitive(definition.Extends))
            {
                typeNames.Add(definition.Extends);
            }

            foreach (var property in definition.Properties)
            {
                AddTypeName(typeNames, property.Type);
            }
        }

        foreach (var operation in groups.SelectMany(x => x.Services).SelectMany(x => x.Operations))
        {
            foreach (var parameter in operation.Parameters)
            {
                AddTypeName(typeNames, parameter.Type);
            }

            if (operation.Return is not null)
            {
                AddTypeName(typeNames, operation.Return.Type);
            }
        }

        return typeNames;
    }

    private static void AddTypeName(HashSet<string> typeNames, string typeName)
    {
        if (HasUsableTypeName(typeName) && !SoapPrimitiveTypes.IsPrimitive(typeName))
        {
            typeNames.Add(typeName);
        }
    }

    private static bool HasUsableTypeName(string? typeName)
    {
        return !string.IsNullOrWhiteSpace(typeName) && !string.IsNullOrWhiteSpace(ToPascalCase(typeName));
    }

    private static void AppendInterface(StringBuilder sb, AxDataContractDefn definition)
    {
        var typeName = ToPascalCase(definition.Name);
        var baseInterface = string.IsNullOrWhiteSpace(definition.Extends)
            ? string.Empty
            : $" : I{ToPascalCase(definition.Extends)}";

        sb.AppendLine($"public interface I{typeName}{baseInterface}");
        sb.AppendLine("{");

        AppendMembers(sb, definition.Properties, includePublicModifier: false, includeInitAccessor: false);

        sb.AppendLine("}");
    }

    private static void AppendUnknownInterface(StringBuilder sb, string typeName)
    {
        var sanitizedTypeName = ToPascalCase(typeName);

        sb.AppendLine($"#warning The definition for type {typeName} is not known. Please check the AOS for the definition.");
        sb.AppendLine($"public interface I{sanitizedTypeName}");
        sb.AppendLine("{");
        sb.AppendLine("}");
    }

    private static void AppendImplementation(StringBuilder sb, AxDataContractDefn definition)
    {
        var typeName = ToPascalCase(definition.Name);
        var baseClass = string.IsNullOrWhiteSpace(definition.Extends)
            ? string.Empty
            : $" : {ToPascalCase(definition.Extends)}, I{typeName}";
        var implementsOnly = string.IsNullOrWhiteSpace(definition.Extends)
            ? $" : I{typeName}"
            : string.Empty;

        sb.AppendLine($"public class {typeName}{baseClass}{implementsOnly}");
        sb.AppendLine("{");

        AppendMembers(sb, definition.Properties, includePublicModifier: true, includeInitAccessor: true);

        sb.AppendLine("}");
    }

    private static void AppendUnknownImplementation(StringBuilder sb, string typeName)
    {
        var sanitizedTypeName = ToPascalCase(typeName);

        sb.AppendLine($"#warning The definition for type {typeName} is not known. Please check the AOS for the definition.");
        sb.AppendLine($"public class {sanitizedTypeName} : I{sanitizedTypeName}");
        sb.AppendLine("{");
        sb.AppendLine("}");
    }

    private static void AppendServices(StringBuilder sb, IEnumerable<DynSvcGroup> groups)
    {
        var validGroups = groups
            .Where(x => HasUsableTypeName(x.Name))
            .OrderBy(x => x.Name, StringComparer.Ordinal)
            .ToList();

        for (int groupIndex = 0; groupIndex < validGroups.Count; groupIndex++)
        {
            var group = validGroups[groupIndex];
            var groupName = ToTypeName(group.Name, "Group");

            sb.AppendLine($"public static class {groupName}");
            sb.AppendLine("{");

            var validServices = group.Services
                .Where(x => HasUsableTypeName(x.Name))
                .OrderBy(x => x.Name, StringComparer.Ordinal)
                .ToList();

            for (int serviceIndex = 0; serviceIndex < validServices.Count; serviceIndex++)
            {
                AppendService(sb, groupName, validServices[serviceIndex]);

                if (serviceIndex != validServices.Count - 1)
                {
                    sb.AppendLine();
                }
            }

            sb.AppendLine("}");

            if (groupIndex != validGroups.Count - 1)
            {
                sb.AppendLine();
                sb.AppendLine();
            }
        }
    }

    private static void AppendRegistrationExtensions(StringBuilder sb, IEnumerable<DynSvcGroup> groups)
    {
        var serviceTypeNames = groups
            .Where(x => HasUsableTypeName(x.Name))
            .SelectMany(x => x.Services)
            .Where(x => HasUsableTypeName(x.Name))
            .Select(x => ToTypeName(x.Name, "Service"))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(x => x, StringComparer.Ordinal)
            .ToList();

        sb.AppendLine("public static class DynamicsEndpointDiscoveryExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static void AddAxServices(IServiceCollection sc, Func<IServiceProvider,IAxCallingService> axCallingFactory)");
        sb.AppendLine("    {");
        sb.AppendLine("        sc.AddScoped<IAxCallingService>(axCallingFactory);");
            
        foreach (var serviceTypeName in serviceTypeNames)
        {
            sb.AppendLine($"        sc.AddScoped<I{serviceTypeName}, {serviceTypeName}>();");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void AppendService(StringBuilder sb, string groupName, DynSvc service)
    {
        var serviceName = ToTypeName(service.Name, "Service");
        var validOperations = service.Operations
            .Where(ShouldGenerateOperation)
            .OrderBy(x => x.Name, StringComparer.Ordinal)
            .ToList();

        sb.AppendLine($"    public interface I{serviceName}");
        sb.AppendLine("    {");

        for (int operationIndex = 0; operationIndex < validOperations.Count; operationIndex++)
        {
            AppendOperationSignature(sb, validOperations[operationIndex]);

            if (operationIndex != validOperations.Count - 1)
            {
                sb.AppendLine();
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    public class {serviceName} : I{serviceName}");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly IAxCallingService _axCallingService;");
        sb.AppendLine();
        sb.AppendLine($"        public {serviceName}(IAxCallingService axCallingService)");
        sb.AppendLine("        {");
        sb.AppendLine("            _axCallingService = axCallingService;");
        sb.AppendLine("        }");

        if (validOperations.Count > 0)
        {
            sb.AppendLine();
        }

        for (int operationIndex = 0; operationIndex < validOperations.Count; operationIndex++)
        {
            AppendOperation(sb, service.ServiceGroupName, service.Name, validOperations[operationIndex]);

            if (operationIndex != validOperations.Count - 1)
            {
                sb.AppendLine();
                sb.AppendLine();
            }
        }

        sb.AppendLine("    }");
    }

    private static bool ShouldGenerateOperation(DynSvcOp operation)
    {
        return HasUsableTypeName(operation.Name) &&
               operation.Return is not null &&
               HasUsableTypeName(operation.Return.Type) &&
               operation.Parameters.Any(x => HasUsableTypeName(x.Type));
    }

    private static void AppendOperation(StringBuilder sb, string groupName, string serviceName, DynSvcOp operation)
    {
        var operationName = ToPascalCase(operation.Name);
        var requestParameter = operation.Parameters.First(x => HasUsableTypeName(x.Type));
        var requestTypeName = ResolveConcreteTypeName(requestParameter.Type);
        var responseTypeName = ResolveConcreteTypeName(operation.Return!.Type);
        var requestArgumentName = ToCamelCase(ToPascalCase(requestParameter.Name));
        var groupLiteral = ToCSharpStringLiteral(groupName);
        var serviceLiteral = ToCSharpStringLiteral(serviceName);
        var operationLiteral = ToCSharpStringLiteral(operation.Name);

        sb.AppendLine($"        public Task<{responseTypeName}> {operationName}({requestTypeName} {requestArgumentName}, CancellationToken ct)");
        sb.AppendLine("        {");
        sb.AppendLine($"            return _axCallingService.MakeRequestAsync<{requestTypeName}, {responseTypeName}>({requestArgumentName}, {groupLiteral}, {serviceLiteral}, {operationLiteral}, ct);");
        sb.AppendLine("        }");
    }

    private static void AppendOperationSignature(StringBuilder sb, DynSvcOp operation)
    {
        var operationName = ToPascalCase(operation.Name);
        var requestParameter = operation.Parameters.First(x => HasUsableTypeName(x.Type));
        var requestTypeName = ResolveConcreteTypeName(requestParameter.Type);
        var responseTypeName = ResolveConcreteTypeName(operation.Return!.Type);
        var requestArgumentName = ToCamelCase(ToPascalCase(requestParameter.Name));

        sb.AppendLine($"        Task<{responseTypeName}> {operationName}({requestTypeName} {requestArgumentName}, CancellationToken ct);");
    }

    private static void AppendMembers(
        StringBuilder sb,
        IReadOnlyCollection<AxDataContractPropertyDefn> properties,
        bool includePublicModifier,
        bool includeInitAccessor)
    {
        var props = properties.OrderBy(x => x.Name, StringComparer.Ordinal).ToList();

        for (int i = 0; i < props.Count; i++)
        {
            var property = props[i];
            sb.AppendLine($"    [JsonProperty(\"{property.Name}\")]");
            sb.AppendLine($"    [JsonPropertyName(\"{property.Name}\")]");

            var modifier = includePublicModifier ? "public " : string.Empty;
            var accessors = includeInitAccessor ? "{ get; init; }" : "{ get; }";
            sb.AppendLine($"    {modifier}{ResolvePropertyType(property)} {ToPascalCase(property.Name)} {accessors}");

            if (i != props.Count - 1)
            {
                sb.AppendLine();
            }
        }
    }

    private static string ResolvePropertyType(AxDataContractPropertyDefn property)
    {
        var elementType = ResolveTypeName(property.Type);
        var propertyType = property.IsCollection
            ? $"IReadOnlyList<{elementType}>"
            : elementType;

        return ShouldBeNullable(property)
            ? $"{propertyType}?"
            : propertyType;
    }

    private static bool ShouldBeNullable(AxDataContractPropertyDefn property)
    {
        return property.IsNullable || property.MinimumOccurances == 0;
    }

    private static string ResolveTypeName(string typeName)
    {
        if (SoapPrimitiveTypes.IsPrimitive(typeName))
        {
            return typeName.ToLowerInvariant() switch
            {
                "anyuri" => "string",
                "boolean" => "bool",
                "byte" => "byte",
                "datetime" => "DateTime",
                "decimal" => "decimal",
                "double" => "double",
                "float" => "float",
                "guid" => "Guid",
                "int" => "int",
                "long" => "long",
                "string" => "string",
                "unsignedbyte" => "byte",
                "unsignedint" => "uint",
                "unsignedlong" => "ulong",
                "unsignedshort" => "ushort",
                _ => typeName
            };
        }

        return $"I{ToPascalCase(typeName)}";
    }

    private static string ResolveConcreteTypeName(string typeName)
    {
        if (SoapPrimitiveTypes.IsPrimitive(typeName))
        {
            return ResolveTypeName(typeName);
        }

        return ToPascalCase(typeName);
    }

    private static string ToCamelCase(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return value;
        }

        return value.Length == 1
            ? value.ToLowerInvariant()
            : char.ToLowerInvariant(value[0]) + value[1..];
    }

    private static string ToTypeName(string value, string suffix)
    {
        var typeName = ToPascalCase(value);
        return typeName.EndsWith(suffix, StringComparison.OrdinalIgnoreCase)
            ? typeName
            : typeName + suffix;
    }

    private static string ToCSharpStringLiteral(string value)
    {
        return $"\"{value.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";
    }

    private static string ToPascalCase(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return value;
        }

        List<string> tokens = [];
        StringBuilder current = new();

        for (int i = 0; i < value.Length; i++)
        {
            char c = value[i];
            if (!char.IsLetterOrDigit(c))
            {
                FlushToken(tokens, current);
                continue;
            }

            if (current.Length > 0 &&
                char.IsUpper(c) &&
                (char.IsLower(current[current.Length - 1]) || char.IsDigit(current[current.Length - 1])))
            {
                FlushToken(tokens, current);
            }

            current.Append(c);
        }

        FlushToken(tokens, current);

        StringBuilder result = new();
        foreach (var token in tokens)
        {
            result.Append(NormalizeToken(token));
        }

        if (result.Length == 0)
        {
            return value;
        }

        if (char.IsDigit(result[0]))
        {
            result.Insert(0, '_');
        }

        return result.ToString();
    }

    private static void FlushToken(List<string> tokens, StringBuilder current)
    {
        if (current.Length == 0)
        {
            return;
        }

        tokens.Add(current.ToString());
        current.Clear();
    }

    private static string NormalizeToken(string token)
    {
        if (token.Length == 0)
        {
            return token;
        }

        if (token.All(char.IsUpper) || token.All(char.IsLower))
        {
            return char.ToUpperInvariant(token[0]) + token[1..].ToLowerInvariant();
        }

        return char.ToUpperInvariant(token[0]) + token[1..];
    }
}
