using System.Text;
using Dev.JoshBrunton.DynamicsEndpointDiscovery.Application.Services.CollectionBuilders.Options;
using Dev.JoshBrunton.DynamicsEndpointDiscovery.Lib.Ax.Services.Soap;
using Dev.JoshBrunton.DynamicsEndpointDiscovery.Lib.Ax.Types;
using Dev.JoshBrunton.DynamicsEndpointDiscovery.Lib.Ax.Types.Soap;

namespace Dev.JoshBrunton.DynamicsEndpointDiscovery.Application.Services.CollectionBuilders;

public class CSharpCollectionBuilder : CollectionBuilderBase<CSharpCollectionBuilderOptions>
{
    public override string BuildCollection(
        IEnumerable<DynSvcGroup> groups,
        SoapTypeCollection types,
        string resource,
        string collectionName,
        CSharpCollectionBuilderOptions options)
    {
        var validDefinitions = types.Definitions
            .Where(x => HasUsableTypeName(x.Name))
            .ToList();
        var definitionsByName = validDefinitions.ToDictionary(x => x.Name, StringComparer.Ordinal);
        var referencedTypeNames = GetReferencedTypeNames(groups, validDefinitions)
            .OrderBy(x => x, StringComparer.Ordinal)
            .ToList();
        var localisations = options.GenerateLocalisationResources
            ? BuildLocalisationContexts(referencedTypeNames, definitionsByName, types.Localisations)
            : new Dictionary<string, CSharpLocalisationContext>(StringComparer.Ordinal);

        StringBuilder sb = new();

        sb.AppendLine($"""
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by a tool.
            //     Environment: {resource}
            //     Date: {DateTime.Now:O}
            //
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------
            """);
        sb.AppendLine("// ReSharper disable All");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        if (options.GenerateLocalisationResources)
        {
            sb.AppendLine("using System.ComponentModel.DataAnnotations;");
        }

        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.Hosting;");
        if (options.IncludeSystemTextJsonAttributes)
        {
            sb.AppendLine("using System.Text.Json.Serialization;");
        }

        if (options.IncludeNewtonsoftJsonAttributes)
        {
            sb.AppendLine("using Newtonsoft.Json;");
        }

        sb.AppendLine();
        sb.AppendLine("#region interfaces");
        sb.AppendLine("public interface IAxCallingService");
        sb.AppendLine("{");
        sb.AppendLine("    Task<TResponse> MakeRequestAsync<TRequest, TResponse>(TRequest request, string groupName, string serviceName, string opName, CancellationToken ct);");
        sb.AppendLine("}");
        sb.AppendLine();

        for (int i = 0; i < referencedTypeNames.Count; i++)
        {
            var typeName = referencedTypeNames[i];
            if (definitionsByName.TryGetValue(typeName, out var definition))
            {
                AppendInterface(sb, definition, options, localisations.GetValueOrDefault(typeName));
            }
            else
            {
                AppendUnknownInterface(sb, typeName);
            }

            if (i != referencedTypeNames.Count - 1)
            {
                sb.AppendLine();
                sb.AppendLine();
            }
        }

        sb.AppendLine("#endregion");
        sb.AppendLine();
        sb.AppendLine("#region implementations");

        for (int i = 0; i < referencedTypeNames.Count; i++)
        {
            var typeName = referencedTypeNames[i];
            if (definitionsByName.TryGetValue(typeName, out var definition))
            {
                AppendImplementation(sb, definition, options, localisations.GetValueOrDefault(typeName));
            }
            else
            {
                AppendUnknownImplementation(sb, typeName);
            }

            if (i != referencedTypeNames.Count - 1)
            {
                sb.AppendLine();
                sb.AppendLine();
            }
        }

        sb.AppendLine("#endregion");
        sb.AppendLine();
        sb.AppendLine("#region services");

        AppendServices(sb, groups);

        sb.AppendLine("#endregion");
        sb.AppendLine();
        if (options.GenerateLocalisationResources)
        {
            sb.AppendLine("#region Resources");

            AppendResources(sb, localisations.Values);

            sb.AppendLine("#endregion");
            sb.AppendLine();
        }

        sb.AppendLine("#region registration");

        AppendRegistrationExtensions(sb, groups);

        sb.AppendLine("#endregion");

        return sb.ToString().TrimEnd();
    }

    private static HashSet<string> GetReferencedTypeNames(
        IEnumerable<DynSvcGroup> groups,
        IEnumerable<AxDataContractDefn> definitions)
    {
        HashSet<string> typeNames = new(StringComparer.Ordinal);

        foreach (var definition in definitions)
        {
            if (!SoapPrimitiveTypes.IsPrimitive(definition.Name))
            {
                typeNames.Add(definition.Name);
            }

            if (!string.IsNullOrWhiteSpace(definition.Extends) && !SoapPrimitiveTypes.IsPrimitive(definition.Extends))
            {
                typeNames.Add(definition.Extends);
            }

            foreach (var property in definition.Properties)
            {
                AddTypeName(typeNames, property.Type);
            }
        }

        foreach (var operation in groups.SelectMany(x => x.Services).SelectMany(x => x.Operations))
        {
            foreach (var parameter in operation.Parameters)
            {
                AddTypeName(typeNames, parameter.Type);
            }

            if (operation.Return is not null)
            {
                AddTypeName(typeNames, operation.Return.Type);
            }
        }

        return typeNames;
    }

    private static void AddTypeName(HashSet<string> typeNames, string typeName)
    {
        if (HasUsableTypeName(typeName) && !SoapPrimitiveTypes.IsPrimitive(typeName))
        {
            typeNames.Add(typeName);
        }
    }

    private static bool HasUsableTypeName(string? typeName)
    {
        return !string.IsNullOrWhiteSpace(typeName) && !string.IsNullOrWhiteSpace(ToPascalCase(typeName));
    }

    private static void AppendInterface(
        StringBuilder sb,
        AxDataContractDefn definition,
        CSharpCollectionBuilderOptions options,
        CSharpLocalisationContext? localisations)
    {
        var typeName = ToPascalCase(definition.Name);
        var baseInterface = string.IsNullOrWhiteSpace(definition.Extends)
            ? string.Empty
            : $" : I{ToPascalCase(definition.Extends)}";

        sb.AppendLine($"public interface I{typeName}{baseInterface}");
        sb.AppendLine("{");

        AppendMembers(sb, definition.Properties, includePublicModifier: false, includeInitAccessor: false, options, localisations);

        sb.AppendLine("}");
    }

    private static void AppendUnknownInterface(StringBuilder sb, string typeName)
    {
        var sanitizedTypeName = ToPascalCase(typeName);

        sb.AppendLine($"#warning The definition for type {typeName} is not known. Please check the AOS for the definition.");
        sb.AppendLine($"public interface I{sanitizedTypeName}");
        sb.AppendLine("{");
        sb.AppendLine("}");
    }

    private static void AppendImplementation(
        StringBuilder sb,
        AxDataContractDefn definition,
        CSharpCollectionBuilderOptions options,
        CSharpLocalisationContext? localisations)
    {
        var typeName = ToPascalCase(definition.Name);
        var baseClass = string.IsNullOrWhiteSpace(definition.Extends)
            ? string.Empty
            : $" : {ToPascalCase(definition.Extends)}, I{typeName}";
        var implementsOnly = string.IsNullOrWhiteSpace(definition.Extends)
            ? $" : I{typeName}"
            : string.Empty;

        AppendDisplayAttribute(sb, string.Empty, localisations?.TypeResource);
        sb.AppendLine($"public class {typeName}{baseClass}{implementsOnly}");
        sb.AppendLine("{");

        AppendMembers(sb, definition.Properties, includePublicModifier: true, includeInitAccessor: true, options, localisations);

        sb.AppendLine("}");
    }

    private static void AppendUnknownImplementation(StringBuilder sb, string typeName)
    {
        var sanitizedTypeName = ToPascalCase(typeName);

        sb.AppendLine($"#warning The definition for type {typeName} is not known. Please check the AOS for the definition.");
        sb.AppendLine($"public class {sanitizedTypeName} : I{sanitizedTypeName}");
        sb.AppendLine("{");
        sb.AppendLine("}");
    }

    private static void AppendServices(StringBuilder sb, IEnumerable<DynSvcGroup> groups)
    {
        var validGroups = groups
            .Where(x => HasUsableTypeName(x.Name))
            .OrderBy(x => x.Name, StringComparer.Ordinal)
            .ToList();

        for (int groupIndex = 0; groupIndex < validGroups.Count; groupIndex++)
        {
            var group = validGroups[groupIndex];
            var groupName = ToTypeName(group.Name, "Group");

            sb.AppendLine($"public static class {groupName}");
            sb.AppendLine("{");

            var validServices = group.Services
                .Where(x => HasUsableTypeName(x.Name))
                .OrderBy(x => x.Name, StringComparer.Ordinal)
                .ToList();

            for (int serviceIndex = 0; serviceIndex < validServices.Count; serviceIndex++)
            {
                AppendService(sb, groupName, validServices[serviceIndex]);

                if (serviceIndex != validServices.Count - 1)
                {
                    sb.AppendLine();
                }
            }

            sb.AppendLine("}");

            if (groupIndex != validGroups.Count - 1)
            {
                sb.AppendLine();
                sb.AppendLine();
            }
        }
    }

    private static void AppendRegistrationExtensions(StringBuilder sb, IEnumerable<DynSvcGroup> groups)
    {
        var serviceTypeNames = groups
            .Where(x => HasUsableTypeName(x.Name))
            .SelectMany(x => x.Services)
            .Where(x => HasUsableTypeName(x.Name))
            .Select(x => ToTypeName(x.Name, "Service"))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(x => x, StringComparer.Ordinal)
            .ToList();

        sb.AppendLine("public static class DynamicsEndpointDiscoveryExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static void AddAxServices(this IServiceCollection sc, Func<IServiceProvider,IAxCallingService> axCallingFactory)");
        sb.AppendLine("    {");
        sb.AppendLine("        sc.AddScoped<IAxCallingService>(axCallingFactory);");
            
        foreach (var serviceTypeName in serviceTypeNames)
        {
            sb.AppendLine($"        sc.AddScoped<I{serviceTypeName}, {serviceTypeName}>();");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void AppendService(StringBuilder sb, string groupName, DynSvc service)
    {
        var serviceName = ToTypeName(service.Name, "Service");
        var validOperations = service.Operations
            .Where(ShouldGenerateOperation)
            .OrderBy(x => x.Name, StringComparer.Ordinal)
            .ToList();

        sb.AppendLine($"    public interface I{serviceName}");
        sb.AppendLine("    {");

        for (int operationIndex = 0; operationIndex < validOperations.Count; operationIndex++)
        {
            AppendOperationSignature(sb, validOperations[operationIndex]);

            if (operationIndex != validOperations.Count - 1)
            {
                sb.AppendLine();
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    public class {serviceName} : I{serviceName}");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly IAxCallingService _axCallingService;");
        sb.AppendLine();
        sb.AppendLine($"        public {serviceName}(IAxCallingService axCallingService)");
        sb.AppendLine("        {");
        sb.AppendLine("            _axCallingService = axCallingService;");
        sb.AppendLine("        }");

        if (validOperations.Count > 0)
        {
            sb.AppendLine();
        }

        for (int operationIndex = 0; operationIndex < validOperations.Count; operationIndex++)
        {
            AppendOperation(sb, service.ServiceGroupName, service.Name, validOperations[operationIndex]);

            if (operationIndex != validOperations.Count - 1)
            {
                sb.AppendLine();
                sb.AppendLine();
            }
        }

        sb.AppendLine("    }");
    }

    private static bool ShouldGenerateOperation(DynSvcOp operation)
    {
        return HasUsableTypeName(operation.Name) &&
               operation.Return is not null &&
               HasUsableTypeName(operation.Return.Type) &&
               operation.Parameters.Any(x => HasUsableTypeName(x.Type));
    }

    private static void AppendOperation(StringBuilder sb, string groupName, string serviceName, DynSvcOp operation)
    {
        var operationName = ToPascalCase(operation.Name);
        var requestParameter = operation.Parameters.First(x => HasUsableTypeName(x.Type));
        var requestTypeName = ResolveConcreteTypeName(requestParameter.Type);
        var responseTypeName = ResolveConcreteTypeName(operation.Return!.Type);
        var requestArgumentName = ToCamelCase(ToPascalCase(requestParameter.Name));
        var groupLiteral = ToCSharpStringLiteral(groupName);
        var serviceLiteral = ToCSharpStringLiteral(serviceName);
        var operationLiteral = ToCSharpStringLiteral(operation.Name);

        sb.AppendLine($"        public Task<{responseTypeName}> {operationName}({requestTypeName} {requestArgumentName}, CancellationToken ct)");
        sb.AppendLine("        {");
        sb.AppendLine($"            return _axCallingService.MakeRequestAsync<{requestTypeName}, {responseTypeName}>({requestArgumentName}, {groupLiteral}, {serviceLiteral}, {operationLiteral}, ct);");
        sb.AppendLine("        }");
    }

    private static void AppendOperationSignature(StringBuilder sb, DynSvcOp operation)
    {
        var operationName = ToPascalCase(operation.Name);
        var requestParameter = operation.Parameters.First(x => HasUsableTypeName(x.Type));
        var requestTypeName = ResolveConcreteTypeName(requestParameter.Type);
        var responseTypeName = ResolveConcreteTypeName(operation.Return!.Type);
        var requestArgumentName = ToCamelCase(ToPascalCase(requestParameter.Name));

        sb.AppendLine($"        Task<{responseTypeName}> {operationName}({requestTypeName} {requestArgumentName}, CancellationToken ct);");
    }

    private static void AppendMembers(
        StringBuilder sb,
        IReadOnlyCollection<AxDataContractPropertyDefn> properties,
        bool includePublicModifier,
        bool includeInitAccessor,
        CSharpCollectionBuilderOptions options,
        CSharpLocalisationContext? localisations)
    {
        var props = properties.OrderBy(x => x.Name, StringComparer.Ordinal).ToList();

        for (int i = 0; i < props.Count; i++)
        {
            var property = props[i];
            AppendDisplayAttribute(sb, "    ", localisations?.Properties.GetValueOrDefault(property.Name));

            if (options.IncludeNewtonsoftJsonAttributes)
            {
                sb.AppendLine($"    [JsonProperty(\"{property.Name}\")]");
            }

            if (options.IncludeSystemTextJsonAttributes)
            {
                sb.AppendLine($"    [JsonPropertyName(\"{property.Name}\")]");
            }

            var modifier = includePublicModifier ? "public " : string.Empty;
            var accessors = includeInitAccessor ? "{ get; init; }" : "{ get; }";
            sb.AppendLine($"    {modifier}{ResolvePropertyType(property)} {ToPascalCase(property.Name)} {accessors}");

            if (i != props.Count - 1)
            {
                sb.AppendLine();
            }
        }
    }

    private static Dictionary<string, CSharpLocalisationContext> BuildLocalisationContexts(
        IReadOnlyCollection<string> referencedTypeNames,
        IReadOnlyDictionary<string, AxDataContractDefn> definitionsByName,
        IEnumerable<AxLabelLocalisation> localisations)
    {
        var labelValues = localisations
            .GroupBy(x => x.LabelId, StringComparer.OrdinalIgnoreCase)
            .ToDictionary(
                x => x.Key,
                x => x.ToDictionary(y => ResolveLanguageSuffix(y.Language), y => y.Value, StringComparer.Ordinal),
                StringComparer.OrdinalIgnoreCase);
        var ret = new Dictionary<string, CSharpLocalisationContext>(StringComparer.Ordinal);

        foreach (var typeName in referencedTypeNames)
        {
            if (!definitionsByName.TryGetValue(typeName, out var definition))
            {
                continue;
            }

            var className = ToPascalCase(definition.Name);
            var resourcesByLanguage = new Dictionary<string, CSharpResourceClass>(StringComparer.Ordinal);
            CSharpResourceReference? typeResource = null;
            Dictionary<string, CSharpResourceReference> propertyResources = [];

            if (labelValues.TryGetValue(definition.LabelId, out var typeValues))
            {
                foreach (var (language, value) in typeValues)
                {
                    var resource = GetOrAddResourceClass(resourcesByLanguage, className, language);
                    resource.Properties[className] = value;
                }

                var displayLanguage = typeValues.Keys.OrderBy(x => x, StringComparer.Ordinal).First();
                typeResource = new CSharpResourceReference($"{className}Resources_{displayLanguage}", className);
            }

            foreach (var property in definition.Properties.Where(x => HasUsableTypeName(x.Name)))
            {
                if (!labelValues.TryGetValue(property.LabelId, out var propertyValues))
                {
                    continue;
                }

                var propertyName = ToPascalCase(property.Name);
                foreach (var (language, value) in propertyValues)
                {
                    var resource = GetOrAddResourceClass(resourcesByLanguage, className, language);
                    resource.Properties[propertyName] = value;
                }

                var displayLanguage = propertyValues.Keys.OrderBy(x => x, StringComparer.Ordinal).First();
                propertyResources[property.Name] = new CSharpResourceReference($"{className}Resources_{displayLanguage}", propertyName);
            }

            if (resourcesByLanguage.Count > 0)
            {
                ret[typeName] = new CSharpLocalisationContext(typeResource, propertyResources, resourcesByLanguage.Values.ToArray());
            }
        }

        return ret;
    }

    private static CSharpResourceClass GetOrAddResourceClass(
        Dictionary<string, CSharpResourceClass> resourcesByLanguage,
        string typeName,
        string language)
    {
        if (!resourcesByLanguage.TryGetValue(language, out var resource))
        {
            resource = new CSharpResourceClass($"{typeName}Resources_{language}", []);
            resourcesByLanguage[language] = resource;
        }

        return resource;
    }

    private static void AppendDisplayAttribute(StringBuilder sb, string indent, CSharpResourceReference? resource)
    {
        if (resource is null)
        {
            return;
        }

        sb.AppendLine($"{indent}[Display(Name = nameof({resource.ClassName}.{resource.PropertyName}), ResourceType = typeof({resource.ClassName}))]");
    }

    private static void AppendResources(StringBuilder sb, IEnumerable<CSharpLocalisationContext> localisations)
    {
        var resources = localisations
            .SelectMany(x => x.ResourceClasses)
            .OrderBy(x => x.Name, StringComparer.Ordinal)
            .ToList();

        for (int i = 0; i < resources.Count; i++)
        {
            var resource = resources[i];
            sb.AppendLine($"public class {resource.Name}");
            sb.AppendLine("{");

            foreach (var property in resource.Properties.OrderBy(x => x.Key, StringComparer.Ordinal))
            {
                sb.AppendLine($"    public static string {property.Key} => {ToCSharpStringLiteral(property.Value)};");
            }

            sb.AppendLine("}");

            if (i != resources.Count - 1)
            {
                sb.AppendLine();
            }
        }
    }

    private static string ResolveLanguageSuffix(string language)
    {
        var primaryLanguage = language.Split('-', StringSplitOptions.RemoveEmptyEntries).FirstOrDefault() ?? language;
        var suffix = ToCamelCase(ToPascalCase(primaryLanguage));
        return string.IsNullOrWhiteSpace(suffix) ? "unknown" : suffix;
    }

    private static string ResolvePropertyType(AxDataContractPropertyDefn property)
    {
        var elementType = ResolveTypeName(property.Type);
        var propertyType = property.IsCollection
            ? $"IReadOnlyList<{elementType}>"
            : elementType;

        return ShouldBeNullable(property)
            ? $"{propertyType}?"
            : propertyType;
    }

    private static bool ShouldBeNullable(AxDataContractPropertyDefn property)
    {
        return property.IsNullable || property.MinimumOccurances == 0;
    }

    private static string ResolveTypeName(string typeName)
    {
        if (SoapPrimitiveTypes.IsPrimitive(typeName))
        {
            return typeName.ToLowerInvariant() switch
            {
                "anyuri" => "string",
                "boolean" => "bool",
                "byte" => "byte",
                "datetime" => "DateTime",
                "decimal" => "decimal",
                "double" => "double",
                "float" => "float",
                "guid" => "Guid",
                "int" => "int",
                "long" => "long",
                "string" => "string",
                "unsignedbyte" => "byte",
                "unsignedint" => "uint",
                "unsignedlong" => "ulong",
                "unsignedshort" => "ushort",
                _ => typeName
            };
        }

        return $"I{ToPascalCase(typeName)}";
    }

    private static string ResolveConcreteTypeName(string typeName)
    {
        if (SoapPrimitiveTypes.IsPrimitive(typeName))
        {
            return ResolveTypeName(typeName);
        }

        return ToPascalCase(typeName);
    }

    private static string ToCamelCase(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return value;
        }

        return value.Length == 1
            ? value.ToLowerInvariant()
            : char.ToLowerInvariant(value[0]) + value[1..];
    }

    private static string ToTypeName(string value, string suffix)
    {
        var typeName = ToPascalCase(value);
        return typeName.EndsWith(suffix, StringComparison.OrdinalIgnoreCase)
            ? typeName
            : typeName + suffix;
    }

    private static string ToCSharpStringLiteral(string value)
    {
        return $"\"{value.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";
    }

    private static string ToPascalCase(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return value;
        }

        List<string> tokens = [];
        StringBuilder current = new();

        for (int i = 0; i < value.Length; i++)
        {
            char c = value[i];
            if (!char.IsLetterOrDigit(c))
            {
                FlushToken(tokens, current);
                continue;
            }

            if (current.Length > 0 &&
                char.IsUpper(c) &&
                (char.IsLower(current[current.Length - 1]) || char.IsDigit(current[current.Length - 1])))
            {
                FlushToken(tokens, current);
            }

            current.Append(c);
        }

        FlushToken(tokens, current);

        StringBuilder result = new();
        foreach (var token in tokens)
        {
            result.Append(NormalizeToken(token));
        }

        if (result.Length == 0)
        {
            return value;
        }

        if (char.IsDigit(result[0]))
        {
            result.Insert(0, '_');
        }

        return result.ToString();
    }

    private static void FlushToken(List<string> tokens, StringBuilder current)
    {
        if (current.Length == 0)
        {
            return;
        }

        tokens.Add(current.ToString());
        current.Clear();
    }

    private static string NormalizeToken(string token)
    {
        if (token.Length == 0)
        {
            return token;
        }

        if (token.All(char.IsUpper) || token.All(char.IsLower))
        {
            return char.ToUpperInvariant(token[0]) + token[1..].ToLowerInvariant();
        }

        return char.ToUpperInvariant(token[0]) + token[1..];
    }

    private sealed record CSharpLocalisationContext(
        CSharpResourceReference? TypeResource,
        IReadOnlyDictionary<string, CSharpResourceReference> Properties,
        IReadOnlyCollection<CSharpResourceClass> ResourceClasses);

    private sealed record CSharpResourceClass(string Name, Dictionary<string, string> Properties);

    private sealed record CSharpResourceReference(string ClassName, string PropertyName);
}
