//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev.JoshBrunton.DynamicsEndpointDiscovery.Rcl.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServiceDiscoveryComponentResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceDiscoveryComponentResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dev.JoshBrunton.DynamicsEndpointDiscovery.Rcl.Resources.Languages.ServiceDiscover" +
                            "yComponentResources", typeof(ServiceDiscoveryComponentResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All done!.
        /// </summary>
        internal static string AllDoneMessage {
            get {
                return ResourceManager.GetString("AllDoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build collection.
        /// </summary>
        internal static string BuildCollection {
            get {
                return ResourceManager.GetString("BuildCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like you cancelled saving the collection. You can always go back and save it again..
        /// </summary>
        internal static string CancelledMessage {
            get {
                return ResourceManager.GetString("CancelledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your collection is ready to go! You can find it here:.
        /// </summary>
        internal static string CollectionReadyMessage {
            get {
                return ResourceManager.GetString("CollectionReadyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to D365.
        /// </summary>
        internal static string ConnectToD365 {
            get {
                return ResourceManager.GetString("ConnectToD365", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro.
        /// </summary>
        internal static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select groups.
        /// </summary>
        internal static string SelectGroups {
            get {
                return ResourceManager.GetString("SelectGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select operations.
        /// </summary>
        internal static string SelectOperations {
            get {
                return ResourceManager.GetString("SelectOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select services.
        /// </summary>
        internal static string SelectServices {
            get {
                return ResourceManager.GetString("SelectServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Endpoint Discovery Wizard.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use this wizard, you&apos;ll need credentials for an Azure app registration with full access to Dynamics 365..
        /// </summary>
        internal static string UsageInstructions1 {
            get {
                return ResourceManager.GetString("UsageInstructions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t know how to get these credentials, talk to an administrator in your organisation..
        /// </summary>
        internal static string UsageInstructions2 {
            get {
                return ResourceManager.GetString("UsageInstructions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Warning:&lt;/b&gt; Excessive use of this tool can result in being temporarily blocked from making requests. It is recommended to use a dedicated app registration that&apos;s not used by any other apps..
        /// </summary>
        internal static string WarningMessage {
            get {
                return ResourceManager.GetString("WarningMessage", resourceCulture);
            }
        }
    }
}
