using Dev.JoshBrunton.DynamicsEndpointDiscovery.Application.Services.CollectionBuilders;
using Dev.JoshBrunton.DynamicsEndpointDiscovery.Application.Services.CollectionBuilders.Options;
using Dev.JoshBrunton.DynamicsEndpointDiscovery.Lib.Ax.Types;
using Dev.JoshBrunton.DynamicsEndpointDiscovery.Lib.Ax.Types.Soap;

namespace Dev.JoshBrunton.DynamicsEndpointDiscovery.Tests.Application.Tests.Tests.Services.CollectionBuilders;

[TestClass]
public class CSharpCollectionBuilderTests
{
    [TestMethod]
    public void ShouldGenerateInterfacesAndImplementationsForDefinitionsAndUnknownReferences()
    {
        var sut = new CSharpCollectionBuilder();
        var groups = new[]
        {
            new DynSvcGroup
            {
                Name = "Sales",
                Services =
                [
                    new DynSvc
                    {
                        Name = "CustomerService",
                        ServiceGroupName = "Sales",
                        Operations =
                        [
                            new DynSvcOp
                            {
                                Name = "GetCustomer",
                                ServiceGroupName = "Sales",
                                ServiceName = "CustomerService",
                                Parameters =
                                [
                                    new DynSvcMethodSymbol
                                    {
                                        Name = "request",
                                        Type = "missing_request"
                                    },
                                    new DynSvcMethodSymbol
                                    {
                                        Name = "ignored",
                                        Type = "   "
                                    }
                                ],
                                Return = new DynSvcMethodSymbol
                                {
                                    Name = "response",
                                    Type = "missingResponse"
                                }
                            }
                        ]
                    }
                ]
            },
            new DynSvcGroup
            {
                Name = "SupportGroup",
                Services =
                [
                    new DynSvc
                    {
                        Name = "Case",
                        ServiceGroupName = "SupportGroup",
                        Operations = []
                    }
                ]
            }
        };
        var types = new SoapTypeCollection
        {
            Samples = new Dictionary<string, string>(),
            Definitions =
            [
                new AxDataContractDefn
                {
                    Name = "customer_record",
                    Extends = string.Empty,
                    Properties =
                    [
                        new AxDataContractPropertyDefn
                        {
                            Name = "customer_name",
                            Type = "string",
                            IsNullable = false,
                            MinimumOccurances = 1,
                            MaximumOccurances = 1
                        },
                        new AxDataContractPropertyDefn
                        {
                            Name = "sales_orders",
                            Type = "sales_order",
                            IsNullable = false,
                            MinimumOccurances = 0,
                            MaximumOccurances = null
                        }
                    ]
                },
                new AxDataContractDefn
                {
                    Name = "preferredCustomer",
                    Extends = "customer_record",
                    Properties =
                    [
                        new AxDataContractPropertyDefn
                        {
                            Name = "credit_limit",
                            Type = "decimal",
                            IsNullable = false,
                            MinimumOccurances = 1,
                            MaximumOccurances = 1
                        }
                    ]
                },
                new AxDataContractDefn
                {
                    Name = "   ",
                    Extends = string.Empty,
                    Properties = []
                }
            ]
        };

        var result = sut
            .BuildCollection(groups, types, "https://example.test", "Collection", new CSharpCollectionBuilderOptions())
            .ToString();

        Assert.IsNotNull(result);
        StringAssert.Contains(result, "<auto-generated>");
        Assert.IsFalse(result.Contains("namespace ", StringComparison.Ordinal));
        StringAssert.Contains(result, "using System.Threading;");
        StringAssert.Contains(result, "using System.Threading.Tasks;");
        StringAssert.Contains(result, "using Microsoft.Extensions.DependencyInjection;");
        StringAssert.Contains(result, "using Microsoft.Extensions.Hosting;");
        StringAssert.Contains(result, "#region interfaces");
        StringAssert.Contains(result, "#endregion");
        StringAssert.Contains(result, "#region implementations");
        StringAssert.Contains(result, "#region services");
        StringAssert.Contains(result, "#region registration");
        StringAssert.Contains(result, "public interface IAxCallingService");
        StringAssert.Contains(result, "Task<TResponse> MakeRequestAsync<TRequest, TResponse>(TRequest request, string groupName, string serviceName, string opName, CancellationToken ct);");
        StringAssert.Contains(result, "public interface ICustomerRecord");
        StringAssert.Contains(result, "[JsonProperty(\"customer_name\")]");
        StringAssert.Contains(result, "[JsonPropertyName(\"customer_name\")]");
        StringAssert.Contains(result, "string CustomerName { get; }");
        StringAssert.Contains(result, "IReadOnlyList<ISalesOrder>? SalesOrders { get; }");
        StringAssert.Contains(result, "public interface IPreferredCustomer : ICustomerRecord");
        StringAssert.Contains(result, "decimal CreditLimit { get; }");
        StringAssert.Contains(result, "#warning The definition for type missing_request is not known. Please check the AOS for the definition.");
        StringAssert.Contains(result, "public interface IMissingRequest");
        StringAssert.Contains(result, "public interface IMissingResponse");
        StringAssert.Contains(result, "public interface ISalesOrder");
        StringAssert.Contains(result, "public class CustomerRecord : ICustomerRecord");
        StringAssert.Contains(result, "public string CustomerName { get; init; }");
        StringAssert.Contains(result, "public IReadOnlyList<ISalesOrder>? SalesOrders { get; init; }");
        StringAssert.Contains(result, "public class PreferredCustomer : CustomerRecord, IPreferredCustomer");
        StringAssert.Contains(result, "public decimal CreditLimit { get; init; }");
        StringAssert.Contains(result, "public class MissingRequest : IMissingRequest");
        StringAssert.Contains(result, "public class MissingResponse : IMissingResponse");
        StringAssert.Contains(result, "public class SalesOrder : ISalesOrder");
        StringAssert.Contains(result, "public static class SalesGroup");
        StringAssert.Contains(result, "public static class SupportGroup");
        StringAssert.Contains(result, "public interface ICustomerService");
        StringAssert.Contains(result, "Task<MissingResponse> GetCustomer(MissingRequest request, CancellationToken ct);");
        StringAssert.Contains(result, "public interface ICaseService");
        StringAssert.Contains(result, "public class CustomerService");
        StringAssert.Contains(result, "public class CaseService");
        StringAssert.Contains(result, "public class CustomerService : ICustomerService");
        StringAssert.Contains(result, "public class CaseService : ICaseService");
        StringAssert.Contains(result, "private readonly IAxCallingService _axCallingService;");
        StringAssert.Contains(result, "public CustomerService(IAxCallingService axCallingService)");
        StringAssert.Contains(result, "public Task<MissingResponse> GetCustomer(MissingRequest request, CancellationToken ct)");
        StringAssert.Contains(result, "return _axCallingService.MakeRequestAsync<MissingRequest, MissingResponse>(request, \"Sales\", \"CustomerService\", \"GetCustomer\", ct);");
        StringAssert.Contains(result, "public static class DynamicsEndpointDiscoveryExtensions");
        StringAssert.Contains(result, "public static void AddAxServices(this IServiceCollection sc, Func<IServiceProvider,IAxCallingService> axCallingFactory)");
        StringAssert.Contains(result, "sc.AddScoped<ICaseService, CaseService>();");
        StringAssert.Contains(result, "sc.AddScoped<ICustomerService, CustomerService>();");
        Assert.IsFalse(result.Contains("public interface I   ", StringComparison.Ordinal));
        Assert.IsFalse(result.Contains("public class    ", StringComparison.Ordinal));
        Assert.IsFalse(result.Contains("nameof(SalesGroup)", StringComparison.Ordinal));
        Assert.IsFalse(result.Contains("SupportGroupGroup", StringComparison.Ordinal));
        Assert.IsFalse(result.Contains("CustomerServiceService", StringComparison.Ordinal));
        Assert.IsFalse(result.Contains(" set; ", StringComparison.Ordinal));
    }
}
