<Project>
    <PropertyGroup>
        <ParentDirectoryBuildPropsPath>
            $([MSBuild]::GetPathOfFileAbove('Directory.Build.props','$(MSBuildThisFileDirectory)..\'))
        </ParentDirectoryBuildPropsPath>
    </PropertyGroup>
    <ImportGroup>
        <Import Project="$(ParentDirectoryBuildPropsPath)" />
    </ImportGroup>

    <PropertyGroup>
        <CsprojName>$([System.IO.Path]::GetFileNameWithoutExtension($(MSBuildProjectFile)))</CsprojName>
        <RootNamespace>Dev.JoshBrunton.DynamicsEndpointDiscovery.$(CsprojName)</RootNamespace>
        <NoWarn>
            $(NoWarn); 
            
            <!-- Source file specified multiple times. This happens with resource designer files. -->
            CS2002
        </NoWarn>
    </PropertyGroup>
</Project>